### PR TITLE
Rc/1.1.1

### PR DESCRIPTION
**Pull request by wajiha-oicr**
Release 1.1.1 to QA

Addresses: 

- https://github.com/icgc-argo/platform-ui/issues/902 (tested in dev)
- 
-

### CODE REVIEW

**Comment by hlminh2000** [comment]
CI is failing here: https://jenkins.qa.cancercollaboratory.org/blue/organizations/jenkins/ARGO%2Fargo-clinical/detail/PR-379/1/pipeline

Are we ready to release this?

**Comment by wajiha-oicr** [comment]
> CI is failing on test here: https://jenkins.qa.cancercollaboratory.org/blue/organizations/jenkins/ARGO%2Fargo-clinical/detail/PR-379/1/pipeline
> 
> Are we ready to release this?

Reran test it seems to be okay now

**Comment by wajiha-oicr** [comment]
@hlminh2000 @blabadi are your changes good to go into qa?

**Comment by hlminh2000** [comment]
docker stuff is good. I guess the test might have some stochastic component...

**Comment by wajiha-oicr** [comment]
I don't have the authorization to merge this btw :laughing:

**Pull request merged**
