### PR TITLE
rc/1.0.1

### PR DESCRIPTION
**Pull request by wajiha-oicr**
Release

### CODE REVIEW

**Comment by blabadi** [comment]
just checking have you tested the change on develop environment and it works as expected ?

**Comment by blabadi** [comment]
@jaserud are you ok with your commit being merged to QA ?

**Comment by jaserud** [comment]
yes, I tested and my stuff is working in dev

**Comment by wajiha-oicr** [comment]
> just checking have you tested the change on develop environment and it works as expected ?

My changes were tested and works

**Pull request merged**
