### PR TITLE
Merge Back 1.44.0

### PR DESCRIPTION
**Pull request by Buwujiu**
**Description of changes**

**Type of Change**

- [ ] Bug
- [ ] Refactor
- [ ] New Feature
- [ ] Release Candidate

**Checklist before requesting review:**

- [ ] Check branch (code change PRs go to `develop` not master)
- [ ] Check copyrights for new files
- [ ] Manual testing
- [ ] Regression tests completed and passing (double check number of tests).
- [ ] Spelling has been checked.
- [ ] Updated swagger docs accordingly (check it's still valid)
- [ ] Set `validationDependency` in meta tag for [Argo Dictionary](https://github.com/icgc-argo/argo-dictionary) fields used in code

### CODE REVIEW

**Review by joneubank — CHANGES_REQUESTED** [review]
No need to update the version in merge back. just keep it at 1.43.1 and then we will know to update it in the RC branch.

**Comment by Buwujiu** [comment]
@joneubank Didn't know why I updated version in merge back, brain was not functioning properly... closing this pr.

**Comment by joneubank** [comment]
LMAO this is my fault. I misread what was happening because I was confused from reading some other Java verison merges. What you did is correct and I'll approve.

**Review by joneubank — APPROVED** [review]
THANKS!

**Pull request merged**
