### PR TITLE
add submitter_specimen_id to validate surgery

### PR DESCRIPTION
**Pull request by ciaranschutte**
**Description of changes**

add submitter_specimen_id to validate surgery

**Type of Change**

- [x] Bug
- [ ] Refactor
- [ ] New Feature
- [ ] Release Candidate

**Checklist before requesting review:**

- [x] Check branch (code change PRs go to `develop` not master)
- [x] Check copyrights for new files
- [x] Manual testing
- [ ] Regression tests completed and passing (double check number of tests).
- [x] Spelling has been checked.
- [x] Updated swagger docs accordingly (check it's still valid)
- [ ] Set `validationDependency` in meta tag for [Argo Dictionary](https://github.com/icgc-argo/argo-dictionary) fields used in code

### CODE REVIEW

**Review by blabadi — APPROVED** [review]
just check the tests please they may caught a regression

**Comment by ciaranschutte** [comment]
test-clinc
`npm run test` not working on `develop` right  now

**Comment by blabadi** [comment]
> test-clinc `npm run test` not working on `develop` right now

that is not what's failing on this branch though https://jenkins.qa.cancercollaboratory.org/blue/organizations/jenkins/ARGO%2Fargo-clinical/detail/feat%2F%23738_Update_Surgery_schema/1/pipeline 

I think some failures are real and most likely tests need to be updated

**Comment by ciaranschutte** [comment]
> > test-clinc `npm run test` not working on `develop` right now
> 
> that is not what's failing on this branch though https://jenkins.qa.cancercollaboratory.org/blue/organizations/jenkins/ARGO%2Fargo-clinical/detail/feat%2F%23738_Update_Surgery_schema/1/pipeline
> 
> I think some failures are real and most likely tests need to be updated

roger!

**Comment by blabadi** [comment]
I checked the last commit on develop it seems to have passed tests, so what you got could be transient failure, give it another shot please

https://jenkins.qa.cancercollaboratory.org/blue/organizations/jenkins/ARGO%2Fargo-clinical/detail/develop/389/pipeline/30

**Comment by Buwujiu** [comment]
Would be nice to update `surgery.tsv` in `sampleFiles/clinical` and add some example rows to cover the validation scenarios.

**Comment by ciaranschutte** [comment]
closing in favour of https://github.com/icgc-argo/argo-clinical/pull/741

**Pull request merged**
